#!/usr/bin/env node

const fs = require('fs');
const mysql_handler = require('./mysql-handler');
const server = require('./server');

const args = process.argv;
var config = JSON.parse(fs.readFileSync('.config'));

function help() {
    let output =
        "Final Project for the course Databases II\n\n"
        + "Commands:\n\n"
        + "db create        creates the database with the configured name\n"
        + "db migrate       migrates the database structure\n"
        + "db ping          checks database connection\n\n"
        + "help             shows available commands\n\n"
        + "server start     starts server with the configured parameters\n\n";
    console.log(output);
}

const commands = {
    'db': () => {
        const subdb = {
            'create': () => {
                mysql_handler.createDatabase(config.mysql.host, config.mysql.user, config.mysql.password, config.mysql.database);
            },
            'migrate': () => {
                mysql_handler.migrateDatabase(config.mysql.host, config.mysql.user, config.mysql.password, config.mysql.database);
            },
            'ping': () => {
                mysql_handler.pingDatabase(config.mysql.host, config.mysql.user, config.mysql.password);
            }
        };
        try {
            subdb[args[3]]();
        }
        catch (err) {
            console.log('Invalid command.');
        }
    },
    'help': help,
    'server': () => {
        const subserver = {
            'start': () => {
                var db = mysql_handler.getConnection(config.mysql.host, config.mysql.user, config.mysql.password, config.mysql.database);
                server.startServer(config.server.host, config.server.port, db);
            }
        };
        try {
            subserver[args[3]]();
        }
        catch (err) {
            console.log('Invalid command.');
        }
    }
}

try {
    commands[args[2]]();
}
catch (err) {
    console.log('Invalid command.');
}